declare const styles: {
  readonly "actionBar": string;
  readonly "active": string;
  readonly "badge": string;
  readonly "badgeCategory": string;
  readonly "badgeMatched": string;
  readonly "badgeNoSchema": string;
  readonly "badgeNotMatched": string;
  readonly "emptyState": string;
  readonly "error": string;
  readonly "fieldGroup": string;
  readonly "fieldLabel": string;
  readonly "pluginContainer": string;
  readonly "previewBox": string;
  readonly "previewLine": string;
  readonly "rowBody": string;
  readonly "rowCard": string;
  readonly "rowFields": string;
  readonly "rowHeader": string;
  readonly "schemaCategory": string;
  readonly "schemaCategoryHeader": string;
  readonly "schemaFieldRow": string;
  readonly "searchBar": string;
  readonly "section": string;
  readonly "sectionLabel": string;
  readonly "tabBar": string;
  readonly "tabContent": string;
  readonly "toolbar": string;
};
export = styles;

